import { Link } from "react-router-dom";
import "../styles/HomePage.css";
import image from "../assets/home-Page.png"

import {
  LockClosedIcon,
  LightBulbIcon,
  UserIcon,
  ArrowTrendingUpIcon, // CORRECTED: Changed from TrendingUpIcon
  PuzzlePieceIcon,
  AcademicCapIcon,
  BriefcaseIcon,
  PaintBrushIcon,
  ChatBubbleBottomCenterTextIcon,
  QuestionMarkCircleIcon,
} from "@heroicons/react/24/outline";

// Helper component for FAQ items for a clean, interactive accordion
const FaqItem = ({ question, children }) => {
  return (
    <details className="faq-item">
      <summary className="faq-question">
        <QuestionMarkCircleIcon className="faq-icon" />
        {question}
      </summary>
      <div className="faq-answer">
        {children}
      </div>
    </details>
  );
};


function HomePage() {
  return (
    <div className="homepage-container">
      {/* --- HERO SECTION --- */}
      <main className="homepage-hero">
        <div className="hero-content">
          <h1 className="hero-title">Unlock Your Focus, One Question at a Time</h1>
          <p className="hero-subtitle">
            Block distractions and turn idle Browse into a learning opportunity. FocusGate uses AI-powered questions to help you stay productive and mindful online.
          </p>
          <Link to="/register" className="hero-cta">
            Get Started for Free
          </Link>
        </div>
        <div className="hero-image">
          <img
            src={image}
            alt="Illustration of focused work"
          />
        </div>
      </main>

      {/* --- KEY FEATURES SECTION --- */}
      <section className="homepage-features">
        <h2 className="section-title">A Smarter Way to Stay Focused</h2>
        <div className="features-grid">
          <div className="feature-item">
            <LockClosedIcon className="feature-icon" />
            <h3>Intelligent Site Locking</h3>
            <p>Block distracting sites. Access them only by answering questions relevant to your goals.</p>
          </div>
          <div className="feature-item">
            <LightBulbIcon className="feature-icon" />
            <h3>AI-Powered Questions</h3>
            <p>Engage with smart, subject-relevant questions generated by AI to match your chosen topics and difficulty.</p>
          </div>
          <div className="feature-item">
            <UserIcon className="feature-icon" />
            <h3>Personalized Profiles</h3>
            <p>Your secure profile stores your performance history, preferred subjects, and custom blocklists.</p>
          </div>
          <div className="feature-item">
            <ArrowTrendingUpIcon className="feature-icon" /> {/* CORRECTED: Changed from TrendingUpIcon */}
            <h3>Adaptive Difficulty</h3>
            <p>Our system adapts to your performance, keeping you challenged and helping you grow.</p>
          </div>
        </div>
      </section>
      
      {/* --- WHO IS IT FOR? SECTION --- */}
      <section className="homepage-usecase">
        <h2 className="section-title">Designed for High-Performers</h2>
        <div className="usecase-grid">
          <div className="usecase-item">
            <AcademicCapIcon className="usecase-icon" />
            <h3>Students</h3>
            <p>Turn study breaks into revision sessions. Block social media and reinforce your learning with questions from your syllabus.</p>
          </div>
          <div className="usecase-item">
            <BriefcaseIcon className="usecase-icon" />
            <h3>Professionals</h3>
            <p>Stay locked-in on deep work. Block news and entertainment sites, ensuring maximum productivity during work hours.</p>
          </div>
          <div className="usecase-item">
            <PaintBrushIcon className="usecase-icon" />
            <h3>Creatives & Developers</h3>
            <p>Maintain your creative flow. Prevent context-switching by locking forums and communities until you solve a relevant problem.</p>
          </div>
        </div>
      </section>

      {/* --- TESTIMONIALS SECTION --- */}
      <section className="homepage-testimonials">
        <h2 className="section-title">Trusted by Users Who Value Their Time</h2>
        <div className="testimonials-grid">
          <blockquote className="testimonial-item">
            <p>"FocusGate completely changed how I study. The AI questions are a brilliant way to make sure I'm not just mindlessly Browse. My grades have actually improved!"</p>
            <footer>— Alex, University Student</footer>
          </blockquote>
          <blockquote className="testimonial-item">
            <p>"As a developer, staying focused is everything. This tool is the only thing that's stopped me from opening Hacker News a hundred times a day. Simple, effective, and smart."</p>
            <footer>— Samantha K., Software Engineer</footer>
          </blockquote>
        </div>
      </section>

      {/* --- FAQ SECTION --- */}
      <section className="homepage-faq">
        <h2 className="section-title">Frequently Asked Questions</h2>
        <div className="faq-container">
          <FaqItem question="How does the AI question generation work?">
            <p>FocusGate integrates with advanced AI models like GPT. Based on the subjects and difficulty you select in your profile, it generates unique questions—including multiple-choice, short answer, and true/false—to ensure you're genuinely engaging your mind.</p>
          </FaqItem>
          <FaqItem question="Is my data and Browse history safe?">
            <p>Absolutely. Your privacy is our priority. The extension operates locally to check for blocked sites, and we only store essential account information like your profile settings and performance history securely on our servers. We never track or sell your Browse data.</p>
          </FaqItem>
          <FaqItem question="Which browsers are supported?">
            <p>Currently, our browser extension is available for Google Chrome. We are actively working on releasing versions for Mozilla Firefox and other major browsers in the near future.</p>
          </FaqItem>
           <FaqItem question="Can I use FocusGate for free?">
            <p>Yes! FocusGate offers a comprehensive free tier that includes all core features like site blocking, AI questions, and performance tracking. We believe everyone should have access to tools that promote better focus.</p>
          </FaqItem>
        </div>
      </section>

      {/* --- FOOTER --- */}
      <footer className="homepage-footer">
        <p>&copy; {new Date().getFullYear()} FocusGate. All rights reserved.</p>
      </footer>
    </div>
  );
}

export default HomePage;